### ISSUE TITLE
Does Windows 10 build version matter?

### ISSUE THREAD

**Issue by y24jds** [hnky/Workshop-AI-Pre#3]
Work Windows laptop has Windows 10 Build 16299.1087.  Is this sufficient? I don't think that I can get them to upgrade it so I might have to use a mac with virtualized windows 10 with your specified build.  Thanks.

**Comment by hnky** [comment]
Hi,

For 1 challenges it does matter what version of windows you run. It has to do with the Windows AI capabilities to run ONNX models.

Henk

**Comment by y24jds** [comment]
Ok.. no worries.. I'll just go with my mac and make sure and get the right version on there before the class.
